[package]
name = "rape-wuwa"
version.workspace = true
edition.workspace = true

[build-dependencies]
cc = "1.0"

[dependencies]
aes-key-finder = { path = "../aes-key-finder" }
pe-utils = { path = "../pe-utils" }
goblin.workspace = true
colored = "3.0.0"