[package]
name = "restorer"
version.workspace = true
edition.workspace = true

[dependencies]
goblin.workspace = true
log.workspace = true
thiserror.workspace = true
colored = "3.0.0"
pe-utils.workspace = true